export { default as Instagram } from './Instagram'
export { default as Twitter } from './Twitter'
export { default as Camera } from './Camera'
export { default as Filter } from './Filter'
export { default as Computer } from './Computer'
